
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://osieaciikvahwbqasozz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zaWVhY2lpa3ZhaHdicWFzb3p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODgwNTAsImV4cCI6MjA1OTk2NDA1MH0.e-hvTzwM3TY48JqdWsmC6RoEzvyl0JBmsYAhEVDoZ-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
